[package]
name = "core-allocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
hwloc = "*"
lazy_static = "*"
log = "*"
nix = "*"

[dev-dependencies]
env_logger = "*"